# Generated by Django 3.2.18 on 2023-04-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_free',
        ),
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='Бесплатно?'),
        ),
    ]
